first alpha release
* format some fmt.Println()

* add some more files for useful data.types
and now QueryNS has worked.

* Add main.go file changed

* add domain.go and query.go

* now ns / a / cname record is working

* Delete main.go

* Delete domain.go

* add design file

* refact some code ,and add some test for package query.

* refact the  order of func return values

* refact code and add some testing

* Refact Domain.go

1, replace yasushi-saito/rbtree with GoLLRB/llrb
 2,refact struct Domain
 3,add MuLLRB struct for both LLRB and Mutex
 4,add init function for this module
 5,add Less func for llrb lib
 6,add some interface for DomainTree and RegionTree (both of them are alias of MuLLRB)

* Delete file Region.go ,and the region definition will be in domain.go

* mv GetDomainResolver() func to query.go to avoid import cycle .

* Add func QuerySOA and TestQuerySOA

 use QuerySOA for Query a domain AS Domain Name ,and use that return NS for query A and CNAME record , if QuerySOA does not return NS record ,than  you can use QueryNS for NS record for special usage.

* Add func QuerySOA and TestQuerySOA

 use QuerySOA for Query a domain AS Domain Name ,and use that return NS for query A and CNAME record , if QuerySOA does not return NS record ,than  you can use QueryNS for NS record for special usage.

* Add More ERROR Values like ERROR_TYPE

* Refact QuerySOA and ParseSOA

Only return *dns.SOA , not []*dns.SOA

* Add ERROR_NOTFOUND  and ERROR_NOTVALID  types

* Add 3 times retry for QueryNS and other refactor

* refact DoQuery  that make Exchange 3 times

* fix line 81 error,delcare ee error at begining

* fix DoQuery loops bugs

* modify QueryA and QueryCNAME param list that got ds/dp

remove  the get ds/dp  logic of  preQuery func

* Add many functions
......

* refact QueryA and other func that return dns.RR_Header instead of interface{}

* add func IpNetToInt32 and change int32 to uint32 in some functions

* refact and rename domain.go

* fix bugs

* fix bugs

* add some func to utils.go and add utils_test.go file

* refact  domain.go , remove ipStart/ipEnd in struct Region

* add wrapper.go and wrapper_test.go

* refact QueryA / QueryCNAME /preQuery .etc ,make srcIP as param

* refact ParseA() and ParseCNAME,add domain name as param and make some check.
 add GetDebugLine() as param in fmt.Println()

* add DebugGetline() func / modify ParseEdnsIPNet /

* add GetARecord() and some testing

* some micro changes

* fix bugs

* add more log

* fix some bugs

* just for some testing

* add tcp retry for dns.TYPEA and dns.TYPECNAME

* just for some testing

* add runtime.GOMAXPROCS setting

* add some testing code for goroutine channel and dns truncated resopnse.

* add A record response to http

* add couter for loop

* Rename Domain.go to domain.go

* Rename Domain_test.go to domain_test.go

* add default Region policy

* add  const variable for default Region policy

* bug fix

* add doQuery() func and Concurrency query for A/CNAME/SOA/NS etc.

* add QueryServe func

* bug fix for Query* that use array as name server param

* bug fix

* bug fix

* bug fix

* add struct RegionNew for query_mysql usage .

* add struct RRNew for query_mysql usage

* change Check_Domain to dns.IsDomainName

* Add query_mysql.go and query_mysql_test.go for mysql backend.

* Add MySQL schema

* Add StrToIP()  func

* Add iplookup module (wrap iplookup.c++ lib by swig)

* add GetIPinfoWithString func to iplookup module and  add iplookup_test.go file.

* add function Int32ToIpNet and some test

* Add config module

* modify data.go for struct tag

* Add new  MySQL schema

* add const DefaultRedaxMask = 32 and change RRNew.Class to uint16 ( based on dns.types.go)

* change with mysql schema changed .

* refact GetARecord and add func GetAFromCache/GetAFromMySQLBackend/GetAFromDNSBackend

* add more debug info

* add func GetCIDRMaskWithUint32Range and test

* modify debug print

* add func GetIpinfoStartEndWithIPString()

* fix bugs for GetCIDRMaskWithUint32Range()

* add iplookup module for get ip range of the client ip,got netaddr / mask for DomainRRCache , replace of use edns client subnet response for region cache. some debug print change.

* add DomainRRCache for both DNSBackend and MySQLBackend, the use the region info from iplookup and mysql RegionTable

* Add get region info from MySQL in func  GetAFromDNSBackend

* Add MySQL schema

* refact GetAFromDNSBackend
change go func routine logic

* Add timer for auto refrech the RegionCache

* add configuration file and parse logic

* fix little bugs and add more debug print

* add config logic for variables , and change the logic

* add IPDB configuration logic for iplookup module

* if there is no region info in region table of mysql db or no info in ipdb , than use edns info for region cache

* check user input ip

* micro changes

* add server/query log configuration

* micro refact

* micro refact

* fix bug for get remoteaddr

* refact variable clientip

* add LogLevel runtime configuration both in config.go and httpdispache.toml

* micro changes

* refact GetDebugline for performance

* add profiling

* add net/http/pprof url router

* confim merge from wangfakang

* add check domain for request domain name

* refact w.writ([]byte) to fmt.Fprint()

* fix bugs: src/server/server.go:104: cannot use "Query for domain: " + query_domain + " is not permited\n" (type string) as type io.Writer in argument to fmt.Fprintln:
	string does not implement io.Writer (missing Write method)

* del som comments and refact utils.InitUitls() to utils.InitLogger

* micro refact

* refact config.go init() to InitConfig(),and invoke in func main() httpDispache.go

* config runtime.GOMAXPROCS(runtime.NumCPU() * 3)  for best performance

* Rejected commit: Default

* micro refact for some variables

* refact RRNew
1,modify RRNew.Target to []string
2,modify GetRRFromMySQL() and TestGetRRFromMySQL()

* change start order for some func

* micro refact for some variables

* change for logs

* merge test case into query_test.go

* add closesig to DoQuery func for multi goroutines

* refact for logs

* add benchmark test for QueryA/QuerySOA/QueryCNAME

* change MuLLRB & MubitRadix
change anoymous struct member ,and add init logic

* fix bugs

* delete constnt.go and mv httpDispacher/httpDispacher.go to main.go

* merge domain module into query module.

* add ClientPool and DnsmsgPool

* remove some comment and add func BenchmarkParseA

* change the default NetworkAddr and NetworkMask value

* change the import order

* change the default NetworkAddr and NetworkMask value

* change sync.Mutex to sync.RWMutex

* add -prof flag to en/disable profiling

* add hello world handle and router

* fixed data race in query.DoQuery()

* micro change

* add radixtree test

* fixed data race in query.DoQuery()

* add radixtree test

* add log format for config

* bugfix: update function NewServer when address already in use and cause core dump

* micro refact

* init regiontree within NewDomainNode()

* little refact

* Add readme.

* add images

* add image