fix bugs: src/server/server.go:104: cannot use "Query for domain: " + query_domain + " is not permited\n" (type string) as type io.Writer in argument to fmt.Fprintln: 	string does not implement io.Writer (missing Write method)